"use client";
import { useState } from "react";
import { updateNotificationPreferences, type NotificationPreferences } from "@/lib/notifications/actions";

const CATEGORIES = [{ key: "partner_invite", label: "Partner Invites" }, { key: "assessment_complete", label: "Assessment Updates" }, { key: "subscription", label: "Subscription" }, { key: "system", label: "System" }] as const;
export function PreferencesForm({ userId, initial }: { userId: string; initial: NotificationPreferences }) {
  const [prefs, setPrefs] = useState(initial); const [status, setStatus] = useState("");
  const toggle = (channel: "email" | "in_app", key: string) => setPrefs((current) => ({ ...current, [channel]: { ...current[channel], [key]: !current[channel][key] } }));
  return <div className="rounded-xl border border-card-border bg-card-bg p-6"><div className="grid grid-cols-[1fr_auto_auto] items-center gap-x-4 gap-y-4 sm:gap-x-5"><div /><h2 className="text-xs font-semibold uppercase tracking-wider text-text-tertiary">Email</h2><h2 className="text-xs font-semibold uppercase tracking-wider text-text-tertiary">In-app</h2>{CATEGORIES.map(({ key, label }) => <div key={key} className="contents"><p className="border-t border-card-border py-4 text-sm font-medium text-text-primary">{label}</p>{(["email", "in_app"] as const).map((channel) => <button key={channel} type="button" role="switch" aria-checked={prefs[channel][key]} onClick={() => toggle(channel, key)} className={`relative mx-auto -m-2 p-2 h-7 w-12 rounded-full transition ${prefs[channel][key] ? "bg-accent-600" : "bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${prefs[channel][key] ? "left-6" : "left-1"}`} /></button>)}</div>)}</div><div className="mt-6 flex flex-wrap items-center gap-4"><button type="button" onClick={async () => { setStatus(""); const result = await updateNotificationPreferences(userId, prefs); setStatus(result.success ? "Preferences saved." : (result.error ?? "Unable to save.")); }} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700">Save preferences</button>{status && <p className="text-sm text-text-secondary">{status}</p>}</div></div>;
}
