const esc = (value: string): string => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char);
const layout = (title: string, body: string, cta?: { label: string; href: string }): string => `<!doctype html><html><body style="margin:0;background:#f8fafc;font-family:Arial,Helvetica,sans-serif;color:#1e293b"><div style="max-width:600px;margin:32px auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden"><div style="background:#1e293b;padding:28px 32px;color:#fff;font-size:20px;font-weight:700">SolidGround <span style="color:#818cf8">AI</span></div><div style="padding:36px 32px"><h1 style="margin:0 0 16px;color:#0f172a;font-size:26px">${title}</h1>${body}${cta ? `<p style="margin:28px 0"><a href="${esc(cta.href)}" style="display:inline-block;background:#4f46e5;color:#fff;padding:13px 22px;border-radius:8px;text-decoration:none;font-weight:600">${esc(cta.label)}</a></p>` : ""}<p style="margin:28px 0 0;color:#64748b;font-size:13px;line-height:1.6">With clarity and confidence,<br/>The SolidGround AI team</p></div></div></body></html>`;
const hello = (name: string): string => `<p style="font-size:16px;line-height:1.7">Hi ${esc(name)},</p>`;
export function WelcomeEmail({ name }: { name: string }): string { return layout("Welcome to SolidGround AI", `${hello(name)}<p style="line-height:1.7">Your Compatibility Blueprint is the first step toward understanding what makes a relationship thrive. We’re glad you’re here.</p>`, { label: "Open your dashboard", href: `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://solidground.ai"}/dashboard` }); }
export function VerifyEmail({ name, link }: { name: string; link: string }): string { return layout("Verify your email", `${hello(name)}<p style="line-height:1.7">Please verify your email address to activate your SolidGround AI account.</p>`, { label: "Verify email address", href: link }); }
export function PasswordResetEmail({ name, link }: { name: string; link: string }): string { return layout("Reset your password", `${hello(name)}<p style="line-height:1.7">We received a request to reset your SolidGround AI password. This link expires soon.</p>`, { label: "Reset password", href: link }); }
export function PartnerInviteEmail({ inviterName, inviteLink }: { inviterName: string; inviteLink: string }): string { return layout(`${esc(inviterName)} invited you to compare Blueprints`, `<p style="line-height:1.7">Someone you care about is ready to explore relationship compatibility with you through SolidGround AI.</p>`, { label: "View invitation", href: inviteLink }); }
export function AssessmentCompleteEmail({ name, score }: { name: string; score: number }): string { return layout("Your Blueprint is ready", `${hello(name)}<p style="line-height:1.7">Your Compatibility Blueprint is complete. Your overall compatibility score is <strong style="color:#4f46e5;font-size:20px">${Math.round(score)}</strong>.</p>`, { label: "View your results", href: `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://solidground.ai"}/dashboard/results` }); }
export function SubscriptionConfirmEmail({ name, plan, amount }: { name: string; plan: string; amount: number }): string { return layout("Subscription confirmed", `${hello(name)}<p style="line-height:1.7">Your <strong>${esc(plan)}</strong> subscription is active at <strong>$${amount.toFixed(2)}</strong>. Thank you for investing in clarity.</p>`, { label: "Manage subscription", href: `${process.env.NEXT_PUBLIC_SITE_URL ?? "https://solidground.ai"}/dashboard/billing` }); }
export function BillingReceiptEmail({ name, amount, date, description }: { name: string; amount: number; date: string; description: string }): string { return layout("Your SolidGround receipt", `${hello(name)}<p style="line-height:1.8"><strong>${esc(description)}</strong><br/>Amount: $${amount.toFixed(2)}<br/>Date: ${esc(date)}</p>`); }
export function CancellationConfirmEmail({ name }: { name: string }): string { return layout("Subscription cancelled", `${hello(name)}<p style="line-height:1.7">Your subscription has been cancelled. You’ll continue to have access through the end of your current billing period.</p>`); }
