import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { BlueprintResults, CategoryResult } from "@/lib/scoring/types";
import type { AIInsights, ComparisonReport, AlignmentResults } from "@/types";

const colors = { navy: "#1e293b", indigo: "#4f46e5", muted: "#64748b", line: "#e2e8f0", soft: "#f8fafc", warning: "#b45309", green: "#166534" };
const styles = StyleSheet.create({ page: { padding: 42, fontFamily: "Helvetica", color: colors.navy, fontSize: 10 }, header: { borderBottomWidth: 2, borderBottomColor: colors.indigo, paddingBottom: 14, marginBottom: 22 }, brand: { color: colors.indigo, fontSize: 11, fontWeight: "bold", letterSpacing: 1.4 }, title: { fontSize: 23, fontWeight: "bold", marginTop: 8 }, subtitle: { color: colors.muted, marginTop: 5 }, section: { marginTop: 18, marginBottom: 8, fontSize: 14, fontWeight: "bold" }, scoreBox: { backgroundColor: colors.soft, borderRadius: 8, padding: 18, flexDirection: "row", alignItems: "center", marginBottom: 16 }, score: { color: colors.indigo, fontSize: 38, fontWeight: "bold", marginRight: 16 }, scoreLabel: { color: colors.muted, fontSize: 10 }, table: { borderWidth: 1, borderColor: colors.line, borderRadius: 5 }, row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: colors.line, padding: 8 }, head: { backgroundColor: colors.soft, fontWeight: "bold" }, cell: { flex: 1 }, cat: { flex: 2 }, text: { lineHeight: 1.45, color: colors.muted }, pill: { padding: 8, backgroundColor: colors.soft, borderRadius: 5, marginBottom: 6 }, warning: { padding: 9, backgroundColor: "#fffbeb", color: colors.warning, borderRadius: 5, marginBottom: 6 }, footer: { position: "absolute", bottom: 24, left: 42, right: 42, borderTopWidth: 1, borderTopColor: colors.line, paddingTop: 6, color: colors.muted, fontSize: 8 } });
const str = (v: unknown): string => typeof v === "string" ? v : v == null ? "" : JSON.stringify(v);
const list = (v: unknown): string[] => Array.isArray(v) ? v.map(str).filter(Boolean) : [];
function Header({ title, name }: { title: string; name: string }) { return <View style={styles.header}><Text style={styles.brand}>SOLIDGROUND AI</Text><Text style={styles.title}>{title}</Text><Text style={styles.subtitle}>{name} · {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</Text></View>; }
function Footer() { return <Text style={styles.footer}>SolidGround AI · Relationship intelligence for intentional partnership</Text>; }
function Score({ value, label = "Overall compatibility score" }: { value: number; label?: string }) { return <View style={styles.scoreBox}><Text style={styles.score}>{Math.round(value)}<Text style={{ fontSize: 16 }}>/100</Text></Text><Text style={styles.scoreLabel}>{label}{"\n"}A structured view of your relationship profile.</Text></View>; }
function Categories({ categories, comparison = false }: { categories: CategoryResult[] | AlignmentResults["categoryAlignments"]; comparison?: boolean }) { if (comparison) { const rows = categories as AlignmentResults["categoryAlignments"]; return <View style={styles.table}><View style={[styles.row, styles.head]}><Text style={styles.cat}>Category</Text><Text style={styles.cell}>You</Text><Text style={styles.cell}>Alignment</Text><Text style={styles.cell}>Partner</Text></View>{rows.map(c => <View style={styles.row} key={c.categoryId}><Text style={styles.cat}>{c.categoryName}</Text><Text style={styles.cell}>{c.inviterScore}</Text><Text style={styles.cell}>{c.alignment}</Text><Text style={styles.cell}>{c.inviteeScore}</Text></View>)}</View>; } const rows = categories as CategoryResult[]; return <View style={styles.table}><View style={[styles.row, styles.head]}><Text style={styles.cat}>Category</Text><Text style={styles.cell}>Score</Text><Text style={styles.cell}>Confidence</Text></View>{rows.map(c => <View style={styles.row} key={c.category}><Text style={styles.cat}>{c.label}</Text><Text style={styles.cell}>{c.score}</Text><Text style={styles.cell}>{c.confidence}%</Text></View>)}</View>; }
function Bullets({ title, items, warning = false }: { title: string; items: string[]; warning?: boolean }) { if (!items.length) return null; return <><Text style={styles.section}>{title}</Text>{items.map((x, i) => <View style={warning ? styles.warning : styles.pill} key={`${x}-${i}`}><Text>{warning ? "⚠ " : "• "}{x}</Text></View>)}</>; }
export function BlueprintDocument({ name, results, insights, relationship = false }: { name: string; results: BlueprintResults; insights?: AIInsights | null; relationship?: boolean }) { const flags = results.categoryResults.filter(c => c.dealBreakerTriggered).map(c => `${c.label} surfaced a potential deal-breaker.`); const strengths = results.categoryResults.sort((a,b) => b.score-a.score).slice(0,3).map(c => `${c.label} (${c.score}%)`); const growth = [...results.categoryResults].sort((a,b) => a.score-b.score).slice(0,3).map(c => `${c.label} (${c.score}%)`); return <Document><Page size="A4" style={styles.page}><Header title={relationship ? "Relationship Blueprint" : "Compatibility Blueprint™"} name={name} /><Score value={results.overallScore} /><Text style={styles.section}>Category breakdown</Text><Categories categories={results.categoryResults} /><Bullets title="Deal-breaker flags" items={flags} warning /><Bullets title="Strengths" items={strengths} /><Bullets title="Growth areas" items={growth} />{relationship && insights && <Insights insights={insights} />}{relationship && !insights && <Text style={styles.text}>AI insights are not available yet. Complete your assessment or return later to generate them.</Text>}<Footer /></Page></Document>; }
function Insights({ insights }: { insights: AIInsights }) { const sections: [string, string[]][] = [["Personal strengths", list(insights.personalStrengths)], ["Growth opportunities", list(insights.growthOpportunities)], ["Reflection questions", list(insights.reflectionQuestions)], ["Communication recommendations", list(insights.communicationRecommendations)]]; return <><Text style={styles.section}>AI insights</Text><Text style={[styles.text, { marginBottom: 8 }]}>{insights.blueprintSummary}</Text><Text style={styles.pill}><Text style={{ fontWeight: "bold" }}>Relationship readiness: </Text>{insights.relationshipReadiness?.level} — {insights.relationshipReadiness?.summary}</Text>{sections.map(([title, items]) => <Bullets key={title} title={title} items={items} />)}</>; }
export function ComparisonDocument({ inviterName, inviteeName, alignment, report }: { inviterName: string; inviteeName: string; alignment: AlignmentResults; report?: ComparisonReport | null }) { const r = report; return <Document><Page size="A4" style={styles.page}><Header title="Partner Comparison" name={`${inviterName} & ${inviteeName}`} /><Score value={r?.overallCompatibility ?? alignment.overallAlignment} label="Overall alignment" /><Text style={styles.section}>Category comparison</Text><Categories categories={r?.categoryComparisons ?? alignment.categoryAlignments} comparison />{r && <><Bullets title="Shared strengths" items={r.sharedStrengths.flatMap(x => [x.categoryName, ...x.questionIds.map(q => `Shared response: ${q}`)])} /><Bullets title="Potential conflicts" items={r.potentialConflicts.map(c => `${c.categoryName} (${c.severity}): ${c.description}`)} warning /><Bullets title="Conversation guides" items={r.conversationGuides.flatMap(g => [g.categoryName + ": " + g.topic, ...g.prompts])} /><Bullets title="Growth opportunities" items={r.growthOpportunities.map(g => `${g.categoryName} (${g.type}): ${g.description}`)} /><Bullets title="Deal-breaker intersections" items={r.dealBreakerIntersections.filter(d => d.bothTriggered).map(d => `${d.categoryName}: both partners triggered a deal-breaker.`)} warning /></>}<Footer /></Page></Document>; }
