-- ============================================================
-- MIGRATION 010: Comparison Reports
-- ============================================================
-- Stores enriched pairwise comparison reports generated by the
-- enhanced alignment engine. One report per pairing.
-- ============================================================

CREATE TABLE IF NOT EXISTS comparison_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pairing_id UUID NOT NULL REFERENCES pairings(id) ON DELETE CASCADE UNIQUE,
  overall_compatibility INTEGER NOT NULL CHECK (overall_compatibility >= 0 AND overall_compatibility <= 100),
  category_comparisons JSONB NOT NULL,
  shared_strengths JSONB NOT NULL,
  potential_conflicts JSONB NOT NULL,
  conversation_guides JSONB NOT NULL,
  growth_opportunities JSONB NOT NULL,
  deal_breaker_intersections JSONB NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_comparison_reports_pairing ON comparison_reports(pairing_id);

ALTER TABLE comparison_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Partners read their comparison reports" ON comparison_reports
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM pairings p
      WHERE p.id = comparison_reports.pairing_id
      AND (p.inviter_user_id = auth.uid() OR p.invitee_user_id = auth.uid())
    )
  );

CREATE POLICY "Service inserts comparison reports" ON comparison_reports
  FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Service updates comparison reports" ON comparison_reports
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM pairings p
      WHERE p.id = comparison_reports.pairing_id
      AND (p.inviter_user_id = auth.uid() OR p.invitee_user_id = auth.uid())
    )
  );
